# PythaiNLP

# Adjust Parameters and test text

In [1]:
test_text = "ส่งผลต่อการพัฒนาเศรษฐกิจโดยตรง"

# Start

In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [6]:
from pythainlp import word_tokenize

# Import Cleaned Data

In [4]:
df = pd.read_csv("dataset_orchid_clean.csv")

In [5]:
df.head(5)

,Unnamed: 0,sentence(x),words,word_with_special_char(y),sentence_without_space(x_clean),binary(y),sentence_len,binary_len
0,0,การประชุมทางวิชาการ ครั้งที่ 1,"['การ', 'ประชุม', 'ทาง', 'วิชาการ', 'ครั้ง', '...","['การ', 'ประชุม', 'ทาง', 'วิชาการ', 'ครั้ง', '...",การประชุมทางวิชาการ ครั้งที่ 1,1001000001001000000100001000,28,28
1,1,โครงการวิจัยและพัฒนาอิเล็กทรอนิกส์และคอมพิวเตอร์,"['โครงการวิจัย', 'และ', 'พัฒนา', 'อิเล็กทรอนิก...","['โครงการวิจัย', 'และ', 'พัฒนา', 'อิเล็กทรอนิก...",โครงการวิจัยและพัฒนาอิเล็กทรอนิกส์และคอมพิวเตอร์,100000000000100100001000000000000010010000000000,48,48
2,2,ปีงบประมาณ 2531,"['ปีงบประมาณ', '2531']","['ปีงบประมาณ', '2531']",ปีงบประมาณ 2531,10000000001000,14,14
3,3,เล่ม 1,"['เล่ม', '1']","['เล่ม', '1']",เล่ม 1,10001,5,5
4,4,ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่ง...,['ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห...,['ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห...,ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่ง...,1000000000000000000000000000000000000000000000...,50,50

# pythai

In [7]:
df['pythainlp'] = df['sentence_without_space(x_clean)'].apply(word_tokenize,keep_whitespace=False)

In [8]:
def to_binary(lst):
    binary_str = ""
    for i in lst:
        binary = '1'
        for j in range(len(i)-1):
            binary = binary+'0'
        binary_str = binary_str+binary
    return(binary_str)

In [9]:
df['pythainlp_binary(y)'] = df['pythainlp'].apply(to_binary)

In [10]:
df.head()

,Unnamed: 0,sentence(x),words,word_with_special_char(y),sentence_without_space(x_clean),binary(y),sentence_len,binary_len,pythainlp,pythainlp_binary(y)
0,0,การประชุมทางวิชาการ ครั้งที่ 1,"['การ', 'ประชุม', 'ทาง', 'วิชาการ', 'ครั้ง', '...","['การ', 'ประชุม', 'ทาง', 'วิชาการ', 'ครั้ง', '...",การประชุมทางวิชาการ ครั้งที่ 1,1001000001001000000100001000,28,28,"[การประชุม, ทางวิชาการ, ครั้ง, ที่, 1]",1000000001000000000100001001
1,1,โครงการวิจัยและพัฒนาอิเล็กทรอนิกส์และคอมพิวเตอร์,"['โครงการวิจัย', 'และ', 'พัฒนา', 'อิเล็กทรอนิก...","['โครงการวิจัย', 'และ', 'พัฒนา', 'อิเล็กทรอนิก...",โครงการวิจัยและพัฒนาอิเล็กทรอนิกส์และคอมพิวเตอร์,100000000000100100001000000000000010010000000000,48,48,"[โครงการ, วิจัยและพัฒนา, อิเล็กทรอนิกส์, และ, ...",100000010000000000001000000000000010010000000000
2,2,ปีงบประมาณ 2531,"['ปีงบประมาณ', '2531']","['ปีงบประมาณ', '2531']",ปีงบประมาณ 2531,10000000001000,14,14,"[ปีงบประมาณ, 2531]",10000000001000
3,3,เล่ม 1,"['เล่ม', '1']","['เล่ม', '1']",เล่ม 1,10001,5,5,"[เล่ม, 1]",10001
4,4,ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่ง...,['ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห...,['ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห...,ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่ง...,1000000000000000000000000000000000000000000000...,50,50,"[ศูนย์, เทคโนโลยี, อิเล็กทรอนิกส์, และ, คอมพิว...",1000010000000010000000000000100100000000001000...

In [49]:
def str_len(lst):
    lst = lst.replace(" ", "")
    return(len(lst))

In [51]:
df['pythainlp_binary_len'] = df['binary(y)'].apply(str_len)

In [57]:
df = df[df['binary_len']==df['pythainlp_binary_len']]

In [143]:
df[df['binary_len']==159]

,Unnamed: 0,sentence(x),words,word_with_special_char(y),sentence_without_space(x_clean),binary(y),sentence_len,binary_len,pythainlp,pythainlp_binary(y),pythainlp_binary_len
11,11,ในการดำเนินการเพื่อให้บรรลุวัตถุประสงค์ดังกล่า...,"['ใน', 'การ', 'ดำเนินการ', 'เพื่อให้', 'บรรลุ'...","['ใน', 'การ', 'ดำเนินการ', 'เพื่อให้', 'บรรลุ'...",ในการดำเนินการเพื่อให้บรรลุวัตถุประสงค์ดังกล่า...,1010010000000010000000100001000000000001000000...,159,159,"[ใน, การ, ดำเนินการ, เพื่อให้, บรรลุ, วัตถุประ...",1010010000000010000000100001000000000001000000...,159
509,517,ทางแผนกชีวอิเล็กทรอนิกส์ คณะวิศวกรรมศาสตร์ สถา...,"['ทาง', 'แผนก', 'ชีวอิเล็กทรอนิกส์', 'คณะ', 'ว...","['ทาง', 'แผนก', 'ชีวอิเล็กทรอนิกส์', 'คณะ', 'ว...",ทางแผนกชีวอิเล็กทรอนิกส์ คณะวิศวกรรมศาสตร์ สถา...,1001000100000000000000001001000000000000010000...,159,159,"[ทาง, แผนก, ชีว, อิเล็กทรอนิกส์, คณะวิศวกรรมศา...",1001000100100000000000001000000000000000010000...,159
696,708,รุ่นที่ 4 (Fourth generation) ในรุ่นนี้จะคล้าย...,"['รุ่น', 'ที่ 4', '<left_parenthesis>', 'Fourt...","['รุ่น', 'ที่4', '(', 'Fourthgeneration', ')',...",รุ่นที่ 4 (Fourth generation) ในรุ่นนี้จะคล้าย...,1000100011000000000000000110100010010100001001...,159,159,"[รุ่น, ที่, 4, (, Fourth, generation, ), ใน, ร...",1000100111000001000000000110100010010100001001...,159
2495,2538,จึงต้องนำมาปรับให้อยู่ในรูปแบบกฎเกณฑ์ที่เหมาะส...,"['จึง', 'ต้อง', 'นำ', 'มา', 'ปรับ', 'ให้', 'อย...","['จึง', 'ต้อง', 'นำ', 'มา', 'ปรับ', 'ให้', 'อย...",จึงต้องนำมาปรับให้อยู่ในรูปแบบกฎเกณฑ์ที่เหมาะส...,1001000101010001001000101000001000000100100000...,159,159,"[จึง, ต้อง, นำมา, ปรับ, ให้, อยู่, ใน, รูปแบบ,...",1001000100010001001000101000001000000100100000...,159
2779,2827,ได้ทดลองบันทึกข้อมูล โดยใช้มาตรฐานโครงสร้างระเ...,"['ได้', 'ทดลอง', 'บันทึก', 'ข้อมูล', 'โดย', 'ใ...","['ได้', 'ทดลอง', 'บันทึก', 'ข้อมูล', 'โดย', 'ใ...",ได้ทดลองบันทึกข้อมูล โดยใช้มาตรฐานโครงสร้างระเ...,1001000010000010000010010010000001000000001000...,159,159,"[ได้, ทดลอง, บันทึก, ข้อมูล, โดย, ใช้, มาตรฐาน...",1001000010000010000010010010000001000000001000...,159
5196,5345,รูปที่ 2 แสดงส่วนต่างๆ ของเตา Horizontal Liqui...,"['รูป', 'ที่ 2', 'แสดง', 'ส่วน', 'ต่างๆ', 'ของ...","['รูป', 'ที่2', 'แสดง', 'ส่วน', 'ต่างๆ', 'ของ'...",รูปที่ 2 แสดงส่วนต่างๆ ของเตา Horizontal Liqui...,1001000100010001000010010000000000000000000000...,159,159,"[รูป, ที่, 2, แสดง, ส่วน, ต่างๆ, ของ, เตา, Hor...",1001001100010001000010010010000000001000001000...,159
6050,6213,อุปกรณ์ต่างๆ ที่ประกอบขึ้นเป็นผลิตภัณฑ์โดยส่วน...,"['อุปกรณ์', 'ต่างๆ', 'ที่', 'ประกอบ', 'ขึ้น', ...","['อุปกรณ์', 'ต่างๆ', 'ที่', 'ประกอบ', 'ขึ้น', ...",อุปกรณ์ต่างๆ ที่ประกอบขึ้นเป็นผลิตภัณฑ์โดยส่วน...,1000000100001001000001000100010000000010010000...,159,159,"[อุปกรณ์, ต่างๆ, ที่, ประกอบ, ขึ้น, เป็น, ผลิต...",1000000100001001000001000100010000000010000000...,159
7719,7916,ผลงานวิจัยในปีแรกนี้ ยังเป็นการวิจัยขั้นพื้นฐา...,"['ผลงานวิจัย', 'ใน', 'ปี', 'แรก', 'นี้', 'ยัง'...","['ผลงานวิจัย', 'ใน', 'ปี', 'แรก', 'นี้', 'ยัง'...",ผลงานวิจัยในปีแรกนี้ ยังเป็นการวิจัยขั้นพื้นฐา...,1000000000101010010010010001001000010000000000...,159,159,"[ผลงานวิจัย, ใน, ปี, แรก, นี้, ยัง, เป็น, การว...",1000000000101010010010010001000000010000000000...,159
10051,10330,"#3 ซึ่งเป็นแกนของนามวลีตามด้วยหน่วยขยาย (Mi, I...","['#3', 'ซึ่ง', 'เป็น', 'แกน', 'ของ', 'นามวลี',...","['#3', 'ซึ่ง', 'เป็น', 'แกน', 'ของ', 'นามวลี',...","#3 ซึ่งเป็นแกนของนามวลีตามด้วยหน่วยขยาย (Mi, I...",1010001000100100100000100100010000000011000000...,159,159,"[#, 3, ซึ่ง, เป็น, แกน, ของ, นามวลี, ตาม, ด้วย...",1110001000100100100000100100010000100011011000...,159
10731,11021,บดินทร์ ทรัพย์สมสมบูรณ์ และสมิทธิ์ สุขสมิทธิ์....,"['บดินทร์', 'ทรัพย์สมสมบูรณ์', 'และ', 'สมิทธิ์...","['บดินทร์', 'ทรัพย์สมสมบูรณ์', 'และ', 'สมิทธิ์...",บดินทร์ ทรัพย์สมสมบูรณ์ และสมิทธิ์ สุขสมิทธิ์....,1000000100000000000000100100000010000000001100...,159,159,"[บดินทร์, ทรัพย์, สม, สมบูรณ์, และ, สมิท, ธิ์,...",1000000100000101000000100100010010010001000100...,159
11193,11489,การวิจัยนี้จะสร้างรูปแบบตัวพิมพ์อักษรไทยในโหมด...,"['การ', 'วิจัย', 'นี้', 'จะ', 'สร้าง', 'รูปแบบ...","['การ', 'วิจัย', 'นี้', 'จะ', 'สร้าง', 'รูปแบบ...",การวิจัยนี้จะสร้างรูปแบบตัวพิมพ์อักษรไทยในโหมด...,1001000010010100001000001000000010000100101000...,159,159,"[การวิจัย, นี้, จะ, สร้าง, รูปแบบ, ตัวพิมพ์, อ...",1000000010010100001000001000000010000100101000...,159
12057,12363,#1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #...,"['#1', '#1', '#1', '#1', '#1', '#1', '#1', '#1...","['#1', '#1', '#1', '#1', '#1', '#1', '#1', '#1...",#1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #1 #...,1010101010101010101010101010101010101010101010...,159,159,"[#, 1, #, 1, #, 1, #, 1, #, 1, #, 1, #, 1, #, ...",1111111111111111111111111111111111111111111111...,159
14666,15066,ภาควิชาวิศวกรรมไฟฟ้า คณะวิศวกรรมศาสตร์ จุฬาลงก...,"['ภาควิชา', 'วิศวกรรมไฟฟ้า', 'คณะ', 'วิศวกรรมศ...","['ภาควิชา', 'วิศวกรรมไฟฟ้า', 'คณะ', 'วิศวกรรมศ...",ภาควิชาวิศวกรรมไฟฟ้า คณะวิศวกรรมศาสตร์ จุฬาลงก...,1000000100000000000010010000000000000100000000...,159,159,"[ภาควิชา, วิศวกรรมไฟฟ้า, คณะวิศวกรรมศาสตร์, จุ...",1000000100000000000010000000000000000100000000...,159
15351,15811,การทำงานในบล๊อคนี้มีวงจรส่วนที่สำคัญสองส่วน ได...,"['การ', 'ทำงาน', 'ใน', 'บล๊อค', 'นี้', 'มี', '...","['การ', 'ทำงาน', 'ใน', 'บล๊อค', 'นี้', 'มี', '...",การทำงานในบล๊อคนี้มีวงจรส่วนที่สำคัญสองส่วน ได...,1001000010100001001010001000100100001001000100...,159,159,"[การทำงาน, ใน, บล๊อค, นี้, มี, วงจร, ส่วน, ที่...",1000000010100001001010001000100100001001000100...,159
18987,19589,ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์ ม...,"['ภาควิชา', 'วิศวกรรมคอมพิวเตอร์', 'คณะ', 'วิศ...","['ภาควิชา', 'วิศวกรรมคอมพิวเตอร์', 'คณะ', 'วิศ...",ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์ ม...,1000000100000000000000000010010000000000000100...,159,159,"[ภาควิชา, วิศวกรรม, คอมพิวเตอร์, คณะวิศวกรรมศา...",1000000100000001000000000010000000000000000100...,159

In [81]:
y = df['binary(y)'].tolist()

In [99]:
pred = df['pythainlp_binary(y)'].tolist()

In [100]:
len(y)

20084

In [101]:
len(pred)

20084

In [147]:
def merge(lst):
    list_merge = ''
    for i in range(len(lst)):
        list_merge = list_merge+lst[i]
    return(list_merge)

In [121]:
list_actual = ''
sum_y = 0
len_y = []
for i in range(len(y)):
    sum_y = sum_y+len(y[i])
    len_y.append(len(y[i]))
    list_actual = list_actual+y[i]

In [123]:
len(len_y)

20084

In [117]:
list_pred = ''
sum_pred = 0
len_pred = []
for i in range(len(pred)):
    sum_pred = sum_pred+len(pred[i])
    len_pred.append(len(pred[i]))
    list_pred = list_pred+pred[i]

In [124]:
len(len_pred)

20084

In [141]:
y[509]

'100100010000000000000000100100000000000001000000000000000000000000000000000000000000000100101001000000000001001000010000001000100010000010010000001001001000100'

In [146]:
len(pred[509].replace(" ", ""))

160

In [149]:
trust_i = []
for i in range(len(len_y)):
    if len_y[i]==len_pred[i]:
        trust_i.append(i)

In [152]:
Y = []
Y_pred = []
for i in trust_i:
    Y.append(y[i])
    Y_pred.append(pred[i])

In [154]:
Y_ = ''
for i in Y:
    Y_ = Y_+i

In [155]:
Y_pred_ = ''
for i in Y_pred:
    Y_pred_ = Y_pred_+i

In [156]:
len(Y_)

1256375

In [157]:
len(Y_pred_)

1256375

In [163]:
Y = list(Y_)
Y_pred = list(Y_pred_)

In [164]:
matrix = confusion_matrix(list(Y),list(Y_pred))

In [165]:
matrix

array([[965123,  34910],
       [ 20743, 235599]], dtype=int64)

In [174]:
print('accuracy_score : ',accuracy_score(list(Y),list(Y_pred)))
print('precision_score : ',precision_score(list(Y),list(Y_pred),pos_label='1'))
print('recall_score : ',recall_score(list(Y),list(Y_pred),pos_label='1'))
print('f1_score : ',f1_score(list(Y),list(Y_pred),pos_label='1'))

accuracy_score :  0.9557035120883495
precision_score :  0.8709469925215058
recall_score :  0.9190807592981252
f1_score :  0.8943667184839736

# Predict test text

In [175]:
test_text = test_text.replace(" ", "")

In [177]:
print('test_text : ',test_text)
print('result_cnn : ',word_tokenize(test_text))

test_text :  ส่งผลต่อการพัฒนาเศรษฐกิจโดยตรง
result_cnn :  ['ส่งผล', 'ต่อ', 'การพัฒนา', 'เศรษฐกิจ', 'โดยตรง']